port:
  clientId: "{{ from env PORT_CLIENT_ID }}" # Can be loaded using environment variable: PORT_CLIENT_ID or OCEAN__PORT__CLIENT_ID
  clientSecret: "{{ from env PORT_CLIENT_SECRET }}" # Can be loaded using environment variable: PORT_CLIENT_SECRET or OCEAN__PORT__CLIENT_SECRET
# The event listener to use for the integration service.
eventListener:
  type: POLLING
integration:
  # The identifier of this integration instance.
  # Can be loaded using environment variable: INTEGRATION_IDENTIFIER or OCEAN__INTEGRATION__IDENTIFIER
  identifier: "{{ from env INTEGRATION_IDENTIFIER }}"
  # These two should match the values in the .port/spec.yaml file
  type: "exporter"
  config:
    cfApiToken: "{{ from env CF_API_TOKEN }}"
    cfAccountId: "{{ from env CF_ACCOUNT_ID }}"