resources:
  - kind: account
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id
          title: '.name'
          blueprint: '"cloudflareAccount"'
  - kind: zone
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id
          title: '.name'
          blueprint: '"cloudflareZone"'
          properties:
            created_at: .created_on
            activated_at: .activated_on
            plan: .plan.name
            status: .status
          relations:
            account: .account.id
  - kind: dns_record
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id
          title: '.name'
          blueprint: '"cloudflareDnsRecord"'
          properties:
            type: .type
            content: .content
            comment: .comment
            ttl: .ttl
            proxiable: .proxiable
            proxied: .proxied
            tags: .tags
          relations:
            zone: .zone_id
  - kind: zerotrust_tunnel
    selector:
      query: .deleted_at == null
    port:
      entity:
        mappings:
          identifier: .id
          title: '.name'
          blueprint: '"cloudflareZeroTrustTunnel"'
          properties:
            created_at: .created_at
            status: .status
            active_inactive_since: if .conns_active_at != null then .conns_active_at else .conns_inactive_at end
            remote_config: .remote_config
          relations:
            account: .account_tag
